name: 'Badge Image Maker'
description: 'Creates an SVG image string from the supplied parameters.'
author: 'TeqBench'

# Define your inputs here.
inputs:
  badge-type:
    description: "Type of badge to create. Options: SUCCESS, FAILURE, INFORMATION"
    required: true
  label:
    description: "The label of the badge."
    required: true
  message:
    description: "The message of the badge."
    required: true
  badge-style:
    description: "The style to use when creating the badge. Options: plastic, flat, flat-square, for-the-badge (default), social"
    required: false
  timestamp-format:
    description: "The datetime format to use when creating a timestamp badge. Options: see exhaustive list in BadgeDateTimeFormatType."
    required: false
  timestamp-timezone:
    description: "The datetime timezone to use when creating a timestamp badge. Options: see exhaustive list in BadgeDateTimeFormatType."
    required: false

# Define your outputs here.
outputs:
  svg:
    description: 'The new badge svg image as a string.'

runs:
  using: node20
  main: dist/index.js
